github:
  target: default
  outputs:
   default:
     type: duckdb
     path: github_contributions.duckdb
     plugins:
     - module: github_contributions.plugin
       alias: pull_requests
       config:
         info: true
